services:
  spotifysaver:
    container_name: spotifysaver
    image: gabrielbaute/spotifysaver:latest
    ports:
      - "3000:3000"
      - "8000:8000"
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URI=${SPOTIFY_REDIRECT_URI}
      - SPOTIFYSAVER_API_HOST=0.0.0.0
      - SPOTIFYSAVER_UI_HOST=0.0.0.0
    volumes:
      - ./music:/music
      - ./config:/config
    command: ["spotifysaver-ui"]
    restart: unless-stopped
