blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Community Questions or Ideas
    url: https://github.com/gabrielbaute/spotify-saver/discussions
    about: Use Discussions for general questions, ideas, or help from the community.
  - name: ðŸ“š Documentation & Wiki
    url: https://github.com/gabrielbaute/spotify-saver/wiki
    about: Check the Wiki for guides, FAQs, and usage examples.